BPF_PUBSUB_BASE_PATH="$(readlink -f $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
BPF_PUBSUB_KERNEL_VERSION="6.8"
BPF_PUBSUB_KERNEL_TARXZ="${BPF_PUBSUB_BASE_PATH}/linux-${BPF_PUBSUB_KERNEL_VERSION}.tar.xz"
BPF_PUBSUB_BMC_PATH="${BPF_PUBSUB_BASE_PATH}/bmc"
